kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: springapp-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: springapp
  name: springapp
spec: {}
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: springapp
  labels:
    app: springapp
    application: springapp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: springapp:latest
  source:
    git:
      ref: main
      uri: https://github.com/github-sree/github-sree.git
    type: Git
    # contextDir: ${CONTEXT_DIR}
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: java:11
        namespace: openshift
      # env:
      #   - name: MAVEN_MIRROR_URL
      #     value: https://artifactory.dhl.com/maven-release
    type: Source
  triggers:
    - github:
        secret: github-secret
      type: GitHub
    - type: Generic
      generic:
        secret: github-secret
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: springapp
  name: springapp
spec:
  replicas: 1
  selector:
    app: springapp
    deploymentconfig: springapp
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: springapp
        deploymentconfig: springapp
    spec:
      volumes:
        -
          name: springapp-data
          persistentVolumeClaim:
            claimName: springapp-data
      containers:
      - image: springapp/springapp:latest
        imagePullPolicy: Always
        name: springapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
            -
              name: springapp-data
              mountPath: /data
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - springapp
      from:
        kind: ImageStreamTag
        name: springapp:latest
    type: ImageChange
---
