 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: spring-volume
 spec:
   resources:
     requests:
       storage: 5Gi
   volumeMode: Filesystem
   accessModes:
     - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-v2
spec:
  selector:
    matchLabels:
      app: spring-app-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-app-v2
    spec:
      containers:
        - name: spring-app-v2
          image: sreedocker0798/spring-app:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /logs
              name: app-volume
              subPath: app-logs
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: spring-volume
            
---