server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  flyway:
    user: sa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update  data:    web:      pageable:        one-indexed-parameters: true
        