server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  flyway:
    user: sa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batchSize: 20#  data:#    web:#      pageable:#        one-indexed-parameters: true
k8sapp:
  jwt:
    cookieName: k8sappCookie
    secret: k8ssecretKey
    expirationMs: 86400000
        