server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  flyway:
    user: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: false
      hibernate.order_inserts: true
      hibernate.jdbc.batch_size: 30
      hibernate.generate_statistics: false#  data:#    web:#      pageable:#        one-indexed-parameters: true
k8sapp:
  jwt:
    cookieName: k8sappCookie
    secret: k8ssecretKey
    expirationMs: 86400000