apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend
spec:
  selector:
    matchLabels:
      app: k8s-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-backend
    spec:
      containers:
        - name: k8s-backend
          env:
          - name: USER_HOME
            value: /home/sree/logs
          image: sreedocker0798/k8s-learning-backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-backend-service
spec:
  selector:
    app: k8s-backend
  ports:
    - protocol: TCP             
      port: 8090
      targetPort: 8090
  type: LoadBalancer
---
