CREATE TABLE ROLES
(
   ROLE_ID VARCHAR (255) NOT NULL,
   ACTIVE BOOLEAN,
   ROLE_NAME VARCHAR (255) NOT NULL,
   PRIMARY KEY (ROLE_ID)
);
CREATE TABLE PRIVILEGE
(
   PRIVILEGE_ID VARCHAR (255) NOT NULL,
   NAME VARCHAR (255) NOT NULL,
   PRIMARY KEY (PRIVILEGE_ID)
);
ALTER TABLE PRIVILEGE ADD CONSTRAINT PRIVIL_UQ_NAME UNIQUE (NAME);
CREATE TABLE ROLES_PRIVILEGES
(
   ROLE_ROLE_ID VARCHAR (255) NOT NULL,
   PRIVILEGES_PRIVILEGE_ID VARCHAR (255) NOT NULL,
   PRIMARY KEY
   (
      ROLE_ROLE_ID,
      PRIVILEGES_PRIVILEGE_ID
   )
);
ALTER TABLE ROLES_PRIVILEGES ADD CONSTRAINT ROLE_PRIVIL_UQ UNIQUE (PRIVILEGES_PRIVILEGE_ID);
ALTER TABLE ROLES_PRIVILEGES ADD CONSTRAINT FKA73LO66EG0YJO6AUAPI0ACNXP FOREIGN KEY (PRIVILEGES_PRIVILEGE_ID) REFERENCES PRIVILEGE;
ALTER TABLE ROLES_PRIVILEGES ADD CONSTRAINT FKUXA2NXCRJKD68J5POLFEGLKR FOREIGN KEY (ROLE_ROLE_ID) REFERENCES ROLES;
CREATE TABLE ROLE_PRIVILEGE_ASSOC
(
   RP_ID VARCHAR (255) NOT NULL,
   PRIVILEGE_ID VARCHAR (255) NOT NULL,
   ROLE_ID VARCHAR (255) NOT NULL,
   PRIMARY KEY (RP_ID)
);
ALTER TABLE ROLE_PRIVILEGE_ASSOC ADD CONSTRAINT FK9MQA5IC5T8TX9PWVEM58U254N FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE;
ALTER TABLE ROLE_PRIVILEGE_ASSOC ADD CONSTRAINT FKNG4DMEH2KDCEBTHLE2V3NPPV0 FOREIGN KEY (ROLE_ID) REFERENCES ROLES;
CREATE TABLE USERS
(
   USER_ID VARCHAR (255) NOT NULL,
   ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL,
   ACCOUNT_NON_LOCKED BOOLEAN NOT NULL,
   CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL,
   EMAIL VARCHAR (255) NOT NULL,
   ENABLED BOOLEAN NOT NULL,
   FIRST_NAME VARCHAR (255),
   LAST_NAME VARCHAR (255) NOT NULL,
   PASSWORD VARCHAR (255) NOT NULL,
   USER_NAME VARCHAR (255) NOT NULL,
   ROLE_ID VARCHAR (255),
   INITIAL_USER BOOLEAN NOT NULL,
   PRIMARY KEY (USER_ID)
);
ALTER TABLE USERS ADD CONSTRAINT EMAIL_UQ UNIQUE (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT USER_NAME_UQ UNIQUE (USER_NAME);
ALTER TABLE USERS ADD CONSTRAINT FKP56C1712K691LHSYEWCSSF40F FOREIGN KEY (ROLE_ID) REFERENCES ROLES